config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "urls#index"

  resources :urls do
    collection do
      get :leader_board
    end

    member do
      get :visit_original
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord

  def make_url_short
    rand(36**8).to_s(36)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :visit_original]
  before_action :validate_url, only: [:show, :visit_original]

  def index
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    @url.title = UlrTitleJob.perform_later(@url.original_url)
    @url.short_url = @url.make_url_short

    if @url.save
      redirect_to @url
    else
      redirect_to urls_path
    end
  end

  def show
  end

  def visit_original
    @url.update(visit_count: (@url.visit_count + 1))
    redirect_to @url.original_url
  end

  def leader_board
    @urls = Url.order(visit_count: :desc).limit(100)
  end

  private

  def set_url
    @url = Url.find(params[:id])
  end

  def validate_url
    redirect_to urls_path if @url.blank?
  end

  def url_params
    params.require(:url).permit(:original_url, :short_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlueCoding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<%= form_for @url, url: urls_path do |f| %>
	<%= f.label :original_url %>
	<%= f.text_field :original_url %>

	<%= f.submit %>
<% end %>
<br>
<%= link_to 'Leader Board', leader_board_urls_path %>

app/views/urls/leader_board.html.erb
<% @urls.each do |url| %>
	<strong>Short Url: </strong> <%= url.short_url %>
	<br>
<% end %>

app/views/urls/show.html.erb
<strong>Original Url:</strong> <%= @url.original_url %>
<br>
<strong>Visited:</strong> <%= @url.visit_count %>
<br>
<strong>Short Url: </strong> <%= link_to "#{@url.short_url}", visit_original_url_path(@url), target: '_blank' %>